### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\G'

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamcli#29]
From [debian bug 1085659](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085659)
```
The SyntaxWarning below were emitted when this package was tested with
pipuarts[1].

Regards
Graham


[1] https://piuparts.debian.org/sid/source/k/kamcli.html


  Setting up kamcli (2.0.0-2) ...
  /usr/lib/python3/dist-packages/kamcli/commands/cmd_db.py:91:
SyntaxWarning: invalid escape sequence '\G'
    scmd = 'mysql -h {0} -u {1} -p{2} -e "select * from {3} \G"
{4}'.format(ctx.gconfig.get('db', 'host'),
```

**Comment by vingarzan** [comment]
I think this might be a false positive - see https://stackoverflow.com/questions/2277014/why-the-g-in-select-from-table-name-g

I'm also using somethings \G if I'm getting a single row back, since that way it's much easier to read and map columns to values - would look like this: https://i0.wp.com/sqlconjuror.com/wp-content/uploads/2021/11/image-23.png?w=667&ssl=1

**Comment by vingarzan** [comment]
Ah, it's python escaping - yeah, that should be probably `scmd = 'mysql -h {0} -u {1} -p{2} -e "select * from {3} \\G"`

**Comment by miconda** [comment]
Thanks, I pushed a commit for it, but line does not seem to match, probably the debian packaged version is before code formatting.
